# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a11d8b64378804ecfa12c9378c6ed306bd174dfaea9b1987907241e69a9c4b89312be786cf81ec7cbb8e12b39b916c5961900c55cb55f7d0b9eebf78a0c2cee9

test:
  secret_key_base: 822d714d6e6bd8296a13d470814e25fd5af5a59f829bd14821d554bc41bd33fb91d26685243c211851ddbb3520077d01238420ad82cc7b041527a86c8efbf22b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
